# permissions for end users to view secretmirrors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretmirror-viewer-role
  labels:
    # Add these permissions to the "view" default role.
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - mirrors.kts.studio
  resources:
  - secretmirrors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mirrors.kts.studio
  resources:
  - secretmirrors/status
  verbs:
  - get
